#cFep配置By LiuNing
[cfg]
#后台TCP端口
app_tcp_port           = 20014

#终端TCP端口
terminal_tcp_port      = 20013

#终端UDP端口
terminal_udp_port      = 20013

#TCP连接超时时间(单位:分钟)
timeout                = 30

#协议类型,0:国网 1:南网 2:广东、浙江规约 3:吉林规约 4:62056-47 5:698测试
ptcl_type              = 0

#是否支持加密(南网使用)
support_compress       = 0

#是否级联(南网使用)
support_cas            = 0

#是否级联终端登陆、心跳(南网使用)
support_cas_link       = 0

#单报文最大字节数(通常1k~2k)
max_frame_bytes        = 2048

#是否支持终端重复登陆(Y/N)
support_comm_terminal  = N

#是否支持前置机维护心跳(Y/N)
is_cfep_reply_heart    = Y

#默认调试级别
#  0 : 打印重要信息
#  1 : 打印重要信息 + 报文日志
#  2 : 打印重要信息 + 报文日志 + 调试信息
default_debug_level    = 0
#默认日志级别
#  0 : 保存重要信息
#  1 : 保存重要信息 + 报文日志
#  2 : 保存重要信息 + 报文日志 + 调试信息
default_log_level    = 2
